# Generated by Django 2.1.5 on 2019-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190119_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_info',
            field=models.CharField(default='Enter status', max_length=1000),
        ),
    ]
