# Generated by Django 2.1.5 on 2019-01-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_picture',
            field=models.FileField(default='default.jpg', upload_to='post_picture'),
        ),
    ]
